#!/usr/bin/perl
use strict;
use warnings;
use Net::OpenSSH;

# Constants
my $VERSION = "1.2.0";
my $HOSTLIST = "$ENV{HOME}/.guesthosts";
my $DEFEDITOR = "/usr/bin/nano";
my $EDITOR = "";
my $USER2PUSH = "guest";
my $number_args = $#ARGV + 1;
my $USERPASS = "";

if ($number_args == 2)
{
	$USER2PUSH = $ARGV[0];
	$USERPASS = $ARGV[1];
}
else
{
	print "Unknown option. Please enter:\n";
	print "pushguest \<UserFile\> \<Password\>\n";
}

if ($ENV{'EDITOR'})
{
        $EDITOR = $ENV{'EDITOR'};
}
else
{
        $EDITOR = $DEFEDITOR;
}


print "pushguest v$VERSION\n";
print "=================\n";
if (! -f $HOSTLIST)
{
	print "Host list file ($HOSTLIST) does not exist. Please create it. One server per line.\n";
	sleep(3);
	system ("$EDITOR $HOSTLIST");
	print "Rerun this script to try again\n";
	exit 0;
};

print "Uploading user $USER2PUSH\n";

chdir "/home/hotlineuser/HotlineFiles/Users";

# Open the host list
open( my $fh => $HOSTLIST) || die "Cannot open $HOSTLIST: $!";

# Loop for each line
while(my $curline = <$fh>)
{
	chop($curline);
	print "Working on server '$curline'\n";
	my $ssh = Net::OpenSSH->new($curline, user => "hotlineuser", password => $USERPASS);
	$ssh->error and die "Couldn't establish SSH connection: ". $ssh->error;
	$ssh->scp_put("$USER2PUSH.yaml", "/home/hotlineuser/HotlineFiles/Users") or die "scp failed: " . $ssh->error;
}
close($fh);

exit 0;

